[package]
name = "test_performance"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.17.1"
gdk-pixbuf = "0.9.0"
rand = "0.8.4"